# Use an official Python runtime as a base image
FROM python:3.8

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . .

# Run app.py when the container launches
CMD ["python", "./app.py"]

# docker build -t hello-world-python .
# docker run hello-world-python
